#!/bin/false
#!/usr/bin/env ansible-playbook

# This is example of per-host playbook.
# Create '<hostname>.yml' with host specific configuration.

- name: apply default role
  gather_facts: true
  connection: local
  hosts: localhost
  vars:
    screen_resolution: 1920x1080
    target_cpu: znver1
  roles:

  - role: hostname
    vars:
      hostname: localhost

  - role: timezone
    vars:
      timezone: Europe/Warsaw

  - role: locale

  - role: unscd

  - role: system_groups

  - role: connman

  - role: resolve_dns_via_localhost

  - role: sshd
    vars:
      no_password_login: True

  - role: dnsmasq
    vars:
      upstream: connman

  - role: system_user
    vars:
      user: foo
      group: users
      additional_groups: audio,video

  - role: clean_tmp_dirs

  - role: disable_wireless_power_saving

  - role: dispatch-conf

  - role: home_files
    vars:
      users:
      - root
      - foo
      deploy:
      - zsh
      - vim
      - tmux
      - colordiff
      - gnupg
      - git

  - role: home_files
    vars:
      users:
      - foo
      deploy:
      - xmodmap
      - gmrun
      - tint2
      - openbox
      - Xdefaults
      - mpv
      - compton

  - role: pam_limits

  - role: in_home_tmpdir

  - role: default_umask_077

  - role: noclear_tty_on_boot

  - role: virtual_memory_tune

  - role: portage

  - role: prefer_ipv4_over_ipv6

  - role: acpid

  - role: sudoers

  - role: moar-network-setup
    vars:
      vm_bridges: '30 31 32'
      vm_bridges_network_prefix: '192.168'
      switch_bridge_interface: br-eth-ports
      switch_bridge_member_interfaces: eth0 eth1
      switch_bridge_subnet: 172.17.17.0/24
      switch_bridge_ip: 172.17.17.1/24
      inbound_open_tcp_ports: 22
      inbound_respond_to_ping: 'true'

  - role: inotify_tune
