# Move dir 'from' to 'to' and leave symlink at the origin.

- name: '{{ move_and_link.from }} state'
  stat:
    path: '{{ move_and_link.from }}'
  register: move_from_to_state

- name: 'move {{ move_and_link.from }} to {{ move_and_link.to }}'
  when: move_from_to_state.stat.exists and not move_from_to_state.stat.islnk
  shell: 'mv "{{ move_and_link.from }}" "{{ move_and_link.to }}"'

- name: '{{ move_and_link.from }} link to {{ move_and_link.to }}'
  file:
    src: '{{ move_and_link.to }}'
    dest: '{{ move_and_link.from }}'
    state: link
